"""
Decline code reference database.
Maps ISO 8583 / Razorpay bank response codes to structured root cause data.
"""

DECLINE_CODE_MAP = {
    "51": {
        "root_cause": "insufficient_funds",
        "confidence": 0.97,
        "description": "Insufficient funds in account. Customer's bank balance is too low.",
        "suggested_channel": "whatsapp",
        "retry_after_hours": 48,
        "can_retry": True,
        "label": "Insufficient Funds",
    },
    "05": {
        "root_cause": "do_not_honor",
        "confidence": 0.85,
        "description": "Bank declined — do not honor. Generic refusal by issuing bank.",
        "suggested_channel": "email",
        "retry_after_hours": 72,
        "can_retry": True,
        "label": "Do Not Honor",
    },
    "14": {
        "root_cause": "invalid_card",
        "confidence": 0.99,
        "description": "Invalid card number. The card number does not exist or has a format error.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Invalid Card",
    },
    "54": {
        "root_cause": "expired_card",
        "confidence": 0.99,
        "description": "Card has expired. Customer needs to update their payment method.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Expired Card",
    },
    "91": {
        "root_cause": "issuer_unavailable",
        "confidence": 0.82,
        "description": "Issuing bank unavailable or unreachable. Temporary network issue.",
        "suggested_channel": "sms",
        "retry_after_hours": 4,
        "can_retry": True,
        "label": "Issuer Unavailable",
    },
    "57": {
        "root_cause": "transaction_not_permitted",
        "confidence": 0.90,
        "description": "Transaction type not permitted on this card by the issuing bank.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Transaction Not Permitted",
    },
    "61": {
        "root_cause": "exceeds_limit",
        "confidence": 0.93,
        "description": "Transaction exceeds the card's withdrawal or transaction limit.",
        "suggested_channel": "whatsapp",
        "retry_after_hours": 24,
        "can_retry": True,
        "label": "Exceeds Limit",
    },
    "65": {
        "root_cause": "exceeds_frequency",
        "confidence": 0.90,
        "description": "Number of allowed transactions in the period has been exceeded.",
        "suggested_channel": "sms",
        "retry_after_hours": 24,
        "can_retry": True,
        "label": "Exceeds Frequency",
    },
    "41": {
        "root_cause": "lost_card",
        "confidence": 0.99,
        "description": "Card reported lost. No retry possible.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Lost Card",
    },
    "43": {
        "root_cause": "stolen_card",
        "confidence": 0.99,
        "description": "Card reported stolen. No retry possible.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Stolen Card",
    },
    "59": {
        "root_cause": "suspected_fraud",
        "confidence": 0.88,
        "description": "Transaction flagged as suspected fraud by the issuing bank.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Suspected Fraud",
    },
    "78": {
        "root_cause": "blocked_first_use",
        "confidence": 0.92,
        "description": "Card blocked — not yet activated for first use.",
        "suggested_channel": "voice",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Not Activated",
    },
    "96": {
        "root_cause": "system_error",
        "confidence": 0.75,
        "description": "System malfunction at the issuing bank. Transient error.",
        "suggested_channel": "sms",
        "retry_after_hours": 2,
        "can_retry": True,
        "label": "System Error",
    },
    "19": {
        "root_cause": "re_enter_transaction",
        "confidence": 0.80,
        "description": "Re-enter transaction. Processing error, can retry.",
        "suggested_channel": "sms",
        "retry_after_hours": 1,
        "can_retry": True,
        "label": "Re-enter Transaction",
    },
    "12": {
        "root_cause": "invalid_transaction",
        "confidence": 0.88,
        "description": "Invalid transaction type for this card.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Invalid Transaction",
    },
    "13": {
        "root_cause": "invalid_amount",
        "confidence": 0.95,
        "description": "Invalid or zero amount submitted.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Invalid Amount",
    },
    "55": {
        "root_cause": "incorrect_pin",
        "confidence": 0.97,
        "description": "Incorrect PIN entered. Customer needs to retry with correct PIN.",
        "suggested_channel": "whatsapp",
        "retry_after_hours": 0,
        "can_retry": True,
        "label": "Incorrect PIN",
    },
    "85": {
        "root_cause": "no_reason_declined",
        "confidence": 0.70,
        "description": "Declined without a specific reason from the bank.",
        "suggested_channel": "whatsapp",
        "retry_after_hours": 24,
        "can_retry": True,
        "label": "No Reason Given",
    },
    "75": {
        "root_cause": "pin_attempts_exceeded",
        "confidence": 0.93,
        "description": "PIN entry attempts exceeded. Card may be temporarily blocked.",
        "suggested_channel": "email",
        "retry_after_hours": 24,
        "can_retry": True,
        "label": "PIN Attempts Exceeded",
    },
    "62": {
        "root_cause": "restricted_card",
        "confidence": 0.90,
        "description": "Restricted card — not permitted for this merchant category.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Restricted Card",
    },
    "R0": {
        "root_cause": "mandate_revoked",
        "confidence": 0.98,
        "description": "Standing instruction / e-mandate has been revoked by the customer.",
        "suggested_channel": "voice",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Mandate Revoked",
    },
    "R1": {
        "root_cause": "mandate_revoked",
        "confidence": 0.98,
        "description": "Customer revoked recurring authorization with their bank.",
        "suggested_channel": "email",
        "retry_after_hours": 0,
        "can_retry": False,
        "label": "Mandate Revoked",
    },
    "NF": {
        "root_cause": "no_funds",
        "confidence": 0.94,
        "description": "Net banking: account has insufficient funds.",
        "suggested_channel": "whatsapp",
        "retry_after_hours": 48,
        "can_retry": True,
        "label": "No Funds",
    },
    "TE": {
        "root_cause": "technical_error",
        "confidence": 0.78,
        "description": "Technical error at the payment gateway. Transient failure.",
        "suggested_channel": "sms",
        "retry_after_hours": 1,
        "can_retry": True,
        "label": "Technical Error",
    },
    "UNKNOWN": {
        "root_cause": "unknown",
        "confidence": 0.50,
        "description": "Unknown decline reason. Requires LLM-based classification.",
        "suggested_channel": "email",
        "retry_after_hours": 24,
        "can_retry": True,
        "label": "Unknown",
    },
}

# Weighted distribution for synthetic data generation
DECLINE_CODE_WEIGHTS = {
    "51": 35,   # insufficient funds (most common)
    "91": 15,   # issuer unavailable
    "54": 12,   # expired card
    "14": 8,    # invalid card
    "05": 10,   # do not honor
    "61": 5,    # exceeds limit
    "96": 5,    # system error
    "85": 4,    # no reason
    "55": 2,    # incorrect pin
    "R0": 2,    # mandate revoked
    "19": 1,    # re-enter
    "TE": 1,    # technical error
}

ROOT_CAUSE_LABELS = {
    "insufficient_funds": "Insufficient Funds",
    "expired_card": "Expired Card",
    "invalid_card": "Invalid Card",
    "do_not_honor": "Do Not Honor",
    "issuer_unavailable": "Issuer Unavailable",
    "mandate_revoked": "Mandate Revoked",
    "suspected_fraud": "Suspected Fraud",
    "transaction_not_permitted": "Not Permitted",
    "system_error": "System Error",
    "technical_error": "Technical Error",
    "no_funds": "No Funds",
    "exceeds_limit": "Exceeds Limit",
    "unknown": "Unknown",
}
